# Generated by Django 2.2.1 on 2019-08-07 14:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_birth',
            field=models.DateField(default=datetime.datetime(2019, 8, 7, 14, 53, 26, 13313, tzinfo=utc), verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_marraige',
            field=models.DateField(default=datetime.datetime(2019, 8, 7, 14, 53, 26, 13313, tzinfo=utc), verbose_name='تاریخ ازدواج'),
        ),
    ]
