# Generated by Django 2.2.1 on 2019-08-07 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190807_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_birth',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_marraige',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ ازدواج'),
        ),
    ]
